encrypt.profile.*:
  type: config_entity
  label: 'Encrypt Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    encryption_method:
      type: string
      label: 'Encryption method selected for encryption profile'
    encryption_key:
      type: string
      label: 'Key ID for encryption profile'
