encrypt.profile.*:
  type: config_entity
  label: 'Encrypt Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    encryption_method:
      type: string
      label: 'Encryption method selected for encryption profile'
    encryption_method_configuration:
      type: encryption_method.config.[%parent.encryption_method]
      label: 'Encryption method configuration'
    encryption_key:
      type: string
      label: 'Key ID for encryption profile'


encryption_method.config.*:
  type: sequence
  label: 'Encryption method config'
  sequence:
    - type: string
